name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: Codigo
        run: npm install

      - name: Verificar Secrets
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          echo "Verificando secrets..."
          if [ -z "${SUPABASE_URL}" ]; then
            echo "Erro: SUPABASE_URL não está configurado!" && exit 1
          fi
          if [ -z "${SUPABASE_KEY}" ]; then
            echo "Erro: SUPABASE_KEY não está configurado!" && exit 1
          fi
          echo "Todos os secrets estão configurados corretamente."

      - name: Run Tests
        working-directory: Codigo
        run: npm test
